### ISSUE TITLE
Unknown symbol in module

### ISSUE THREAD

**Issue by orf53975** [m0nad/Diamorphine#11]
Centos
2.6.32-431.el6.x86_64

`/sbin/insmod diamorphine.ko
insmod: error inserting 'diamorphine.ko': -1 Unknown symbol in module
`

**Comment by rtw49418** [comment]
CentOS
uname -r
3.10.0-693.21.1.el7.x86_64

dmesg | tail -n 1
diamorphine: Unknown symbol __check_object_size (err 0)

**Comment by m0nad** [comment]
@rtw49418 and @orf53975 Diamorphine was compile in this same environment?

**Comment by rtw49418** [comment]
> @rtw49418 and @orf53975 Diamorphine was compile in this same environment?

of course that , what I miss?

**Comment by rtw49418** [comment]
Thanks for your replay!
and I add kernel module sign, do not help


hexdump -C diamorphine.ko | tail
0004a600  c1 43 28 10 50 f2 2c 19  fb 10 96 1d 89 64 90 83  |.C(.P.,......d..|
0004a610  7f e6 a4 64 b6 9b e0 2c  78 c7 88 a5 5c a8 94 cd  |...d...,x...\...|
0004a620  06 49 b4 75 79 9f 37 06  7d ed f0 f0 08 01 bd bd  |.I.uy.7.}.......|
0004a630  a5 1d 2b c3 e1 32 3e 4a  82 bb 94 73 7e b9 88 29  |..+..2>J...s~..)|
0004a640  06 d0 58 3b 22 eb c8 19  40 1f 4e 04 45 70 b1 fc  |..X;"...@.N.Ep..|
0004a650  96 6b 25 fa 06 35 0f 7c  b7 e6 27 40 1d 5c ac 40  |.k%..5.|..'@.\.@|
0004a660  c4 03 5d 09 e2 ba 01 04  01 18 14 00 00 00 00 00  |..].............|
0004a670  02 02 7e 4d 6f 64 75 6c  65 20 73 69 67 6e 61 74  |..~Module signat|
0004a680  75 72 65 20 61 70 70 65  6e 64 65 64 7e 0a        |ure appended~.|




insmod: ERROR: could not insert module diamorphine.ko: Unknown symbol in module

**Comment by m0nad** [comment]
I just tested on CentOS release 6.5 with kernel 2.6.32-754.35.1.el6.x86_64. It's not the same kernel but it's pretty close, and everything worked as expected. I will close the issue, but reopen in case that you still have problems.
