### ISSUE TITLE
Compilation Errors on CentOS 5.8 - Kernel 2.6.18-308.16.1.el5

### ISSUE THREAD

**Issue by mukesh-610** [m0nad/Diamorphine#16]
I'm getting a bunch of "undefined syscall number" errors.

    diamorphine.c: In function ‘get_syscall_table_bf’:
    diamorphine.c:46: error: ‘__NR_close’ undeclared (first use in this function)
    diamorphine.c:46: error: (Each undeclared identifier is reported only once
    diamorphine.c:46: error: for each function it appears in.)
    diamorphine.c: In function ‘diamorphine_init’:
    diamorphine.c:299: error: ‘__NR_getdents’ undeclared (first use in this function)
    diamorphine.c:300: error: ‘__NR_getdents64’ undeclared (first use in this function)
    diamorphine.c:301: error: ‘__NR_kill’ undeclared (first use in this function)
    diamorphine.c: In function ‘diamorphine_cleanup’:
    diamorphine.c:316: error: ‘__NR_getdents’ undeclared (first use in this function)
    diamorphine.c:317: error: ‘__NR_getdents64’ undeclared (first use in this function)
    diamorphine.c:318: error: ‘__NR_kill’ undeclared (first use in this function)

Am I missing any packages?

    Kernel 2.6.18-308.16.1.el5
    gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-52)

**Comment by mukesh-610** [comment]
Wow. Just as I finished typing this comment, I found the relevant definitions in `asm/unistd.h`. I just put `#include <asm/unistd.h>` on the top in `diamorphine.c` and it compiled perfectly.

**Comment by m0nad** [comment]
Thanks for reporting, but I need to investigate the issue.

**Comment by m0nad** [comment]
Compilation should work now.
