### ISSUE TITLE
Questions about hidden processes and display modules

### ISSUE THREAD

**Issue by skr-rks** [m0nad/Diamorphine#19]
Centos8 zhōng kernel wèi 4.18. Zhíxíng kill -63 0 hòu biāoqiān yè bèi guānbì, mókuài wèi xiǎnshì. Érqiě kill 31 PID yǐncáng jìnchéng hòu wúfǎ huīfù, tíshì gāi jìnchéng ID bù cúnzài.
80/5000
The kernel in centos8 is 4.18. After executing kill -63 0, the tab page is closed and the module is not displayed. And the kill 31 PID cannot be recovered after hiding the process, indicating that the process ID does not exist.

**Comment by m0nad** [comment]
At the moment, Diamorphine is not working properly in kernels above 4.16. If you manage to fix this, please send a pull request.

**Comment by m0nad** [comment]
Tested on CentOS 8.2 with kernel 4.18.0-193.14.2.el8_2.x86_64 and everything work as expected. Can you provide the exact CentOS and the kernel version?
![Screenshot from 2020-08-31 01-29-21](https://user-images.githubusercontent.com/772792/91671777-cb95cc80-eb29-11ea-92f5-9d2ed602da10.png)
