### ISSUE TITLE
Bad link to LKM hacking article

### ISSUE THREAD

**Issue by superswan** [m0nad/Diamorphine#28]
Link to thc.org for LKM article is stale. 

Suggested Alternatives:
http://www.ouah.org/LKM_HACKING.html
[Archived Link](https://web.archive.org/web/20130701012611/https://www.thc.org/papers/LKM_HACKING.html
)

**Comment by m0nad** [comment]
Thanks for letting me know, I choose to use web archive to keep the original link.
