### ISSUE TITLE
linux 6.3 can support

### ISSUE THREAD

**Issue by clywm520** [m0nad/Diamorphine#39]
linux 6.3 can support?

**Comment by m0nad** [comment]
I just tested on Linux fedora 6.4.15-200.fc38.x86_64 and everything worked as expected. So, yes :)

**Comment by clywm520** [comment]
make[1]: 进入目录“/usr/src/kernels/6.3.0-1.el7.elrepo.x86_64”

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make[1]: *** [Makefile:801：include/config/auto.conf] 错误 1
make[1]: 离开目录“/usr/src/kernels/6.3.0-1.el7.elrepo.x86_64”
make: *** [Makefile:7：all] 错误 2

**Comment by clywm520** [comment]
centos7

**Comment by clywm520** [comment]
已经验证6.4.13内核是OK的

**Comment by m0nad** [comment]
Thanks for reporting, reopening this

**Comment by m0nad** [comment]
Make sure you have the kernel-devel package installed: `sudo yum install kernel-devel`
