### ISSUE TITLE
how to hide tcp port?

### ISSUE THREAD

**Issue by carpediem01** [m0nad/Diamorphine#5]
Look forward to your soonest reply！
 Hi, i have   two  questions.
First,i  created   a  file  named MAGIC_PREFIX-test.py。But  it  can be found  .

Second, how  ti      hide   tcp   port.

Thanks!

**Comment by m0nad** [comment]
1 - The MAGIC_PREFIX is defined in the diamorphine.h to "diamorphine_secret", ex: diamorphine_secret_test.py.
2 - Diamorphine doesn't support hide tcp ports.
