### ISSUE TITLE
make: *** /lib/modules/4.9.51-10.52.amzn1.x86_64/build: No such file or directory.  Stop.

### ISSUE THREAD

**Issue by aidylewis** [m0nad/Diamorphine#6]
Development tools are installed on a 64 bit Fedora based machine.

```
Diamorphine]$ make
make -C /lib/modules/4.9.51-10.52.amzn1.x86_64/build M=/home/ec2-user/maK_it-Linux-Rootkit/Diamorphine modules
make: *** /lib/modules/4.9.51-10.52.amzn1.x86_64/build: No such file or directory.  Stop.
make: *** [all] Error 2
[ec2-user@ip-172-31-15-233 Diamorphine]$ uname -r
4.9.51-10.52.amzn1.x86_64
```

**Comment by m0nad** [comment]
Have you install the kernel headers? It's needed to compile kernel modules like Diamorphine, what distro it is?

**Comment by aidylewis** [comment]
Yes, it is kernel headers. I was using Amazon linux to do some pen testing. I wondering how hackers get these rootkits installed when we need kernel headers that don't seem to be installed by default. Thanks for the help.
