### ISSUE TITLE
how Hide/unhide any process? 

### ISSUE THREAD

**Issue by 630036435** [m0nad/Diamorphine#8]
how Hide/unhide any process?

**Comment by 630036435** [comment]
replace   #define PF_INVISIBLE 0x10000000  ?
0x10000000   is a  pid ?

**Comment by Theldus** [comment]
@630036435 looks like the syscall kill() is overwritten, so, in theory, after load this kernel module, you just have to send a signal from the terminal by using the kill command and the SIGINVIS signal (31).
Something like: `$ kill -31 pid`. =)
