### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by cryptosk** [m0nad/Diamorphine#9]
I'd be willing to donate 0.2 BTC if you can make it hide CPU usage of specified process as well and another 0.1 BTC for capability to run a file every X hours.

**Comment by BAKMAH** [comment]
already done - https://github.com/alex91ar/Diamorphine

**Comment by cryptosk** [comment]
Nice find! 
This however fakes the load average of the entire system, I'd prefer if only the specified process is hidden.

Also looking to replace cron entirely by having the module run executable every X hours..
